sudo: required

language: csharp
cache:
  directories:
  - $PWD/packages

services:
  - docker

script:
  - docker build -t webapp:test -f dockerfiles/test .
  - docker run -it -v $PWD/packages:/root/.nuget/packages webapp:test

after_success:
  - docker build -t webapp:release -f dockeriles/release .
  - docker tag webapp:release xaviercl/webapp:latest
  - docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
  - docker push xaviercl/webapp:latest